client:
    when: manual
    image: weboaks/node-karma-protractor-chrome:alpine-root
    before_script:
    - npm run install:client
    tags:
      - revision

publish:
    before_script:
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | base64 --decode | ssh-add -
    script:
    - hostname -I
    - 'ssh -A -o StrictHostKeyChecking=no gitworker@$IP "cd /home/gitworker && touch hello.txt"'