client:
    when: manual
    image: oyvindlg/gitlab-ci-library:ansible-cgi
    script:
    - yum -y install epel-release nodejs
    - eval $(ssh-agent -s)
    - echo "$WORKER_PRIVATE_KEY" | base64 --decode | ssh-add -
    - npm run install:client
    - npm run build:client
    - scp -o "StrictHostKeyChecking=no" -r /builds/revision/revision-visualization/client/build gitworker@158.39.77.144:/var/www/html/revision-visualization/client/
    tags:
      - revision