client:
    when: manual
    image: weboaks/node-karma-protractor-chrome:alpine-root
    before_script:
    - npm run install:client
    #- eval $(ssh-agent -s)
    #- echo "$PRIVATE_KEY" | base64 --decode | ssh-add -
    tags:
      - revision

    script:
    - npm run build:client
    #- hostname -I
    #- 'ssh -A -o StrictHostKeyChecking=no gitworker@pva.uib.no "cd /var/www/vimd && git pull origin deployment"'