client:
    when: manual
    image: oyvindlg/gitlab-ci-library:ansible-cgi
    before_script:
    - yum -y install epel-release nodejs
    - echo node --version
    - eval $(ssh-agent -s)
    - echo "$WORKER_PRIVATE_KEY" | base64 --decode | ssh-add -
    - npm run install:client
    script:
    - /builds/revision/revision-visualization/client/build
    - pwd
    - hostname -I
    - 'ssh -A -o StrictHostKeyChecking=no gitworker@158.39.77.144 "cd /home/gitworker && touch hello.txt"'
    tags:
      - revision